
export const config = {
    excerptSizeInChars: 450,
    indexPostsPerPage: 4,
    defaultThemeMode: 'dark',
    siteName: 'blog.flashsoft.eu',
    siteIndexTitle: 'Blog | flashsoft.eu',
    siteIndexDescription: 'Blog | flashsoft.eu all kinds of articles mainly tech and web development adjacent by andrei0x309',
    baseSiteUrl: 'https://blog.flashsoft.eu',
    echoCommentsEnabled: true,
    echoTipsEnabled: true,
    echoReciverAddress: 'andrei0x309.eth',
    authorPageEnabled: true,
    relatedPostsEnabled: true,
    signatureDisplayEnabled: true,
    enableGoogleAnalytics: true,
    googleAnalyticsId: 'G-0TYDTZGHS4',
    supportedLanguages: [ 'en', 'ro' ],
    footerSocialIcons: {
        github: true,
        pinterest: true,
        twitter: true,
        tiktok: true,
    },
    // -1 to disable the feature, 0 to show all links, any other number to show that number of links
    numLinksForAuthor: 0,
}

// Use empty string if you don't want to include a social link
export const schemaSocials = {
    facebook: '',
    linkedin: '',
    twitter: 'https://twitter.com/andrei0x309',
    instagram: 'https://www.instagram.com/andrei0x309_',
    youtube: 'https://www.youtube.com/@andrei0x309',
    github: 'https://github.com/andrei0x309',
    gitlab: 'https://gitlab.com/andrei0x309',
    stackoverflow: 'https://stackoverflow.com/users/4354506/andrei-o',
    twitch: 'https://www.twitch.tv/andrei0x309',
    reddit: 'https://www.reddit.com/user/andrei0x309',
    mirror: 'https://mirror.xyz/andrei0x309.eth',
    discord: 'https://discordhub.com/profile/556064803203055616',
    telegram: 'https://t.me/andrei0x309',
    tiktok: 'https://www.tiktok.com/@andrei0x309',
    pinterest: 'https://www.pinterest.com/andrei0x309',
    spotify: 'https://open.spotify.com/user/31j4le3alu4ezqp3ymyroyt5vk7y',
    soundcloud: '',
    vimeo: '',
    medium: '',
    quora: '',
    devto: '',
    snapchat: '',
    hackernews: '',
    behance: '',
    dribbble: '',
    threads: '',
    bluesky: '',
}
